import AuthContext from "@/context/AuthContext";
import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";
import Provider from "@/redux/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="inset-0 bg-zinc-900 fixed flex"></div>
				<div className="text-gray-100 relative max-w-4xl mx-auto ">
					<AuthContext>
						<Provider>
							<main>{children}</main>
						</Provider>
					</AuthContext>
				</div>
			</body>
		</html>
	);
}
